spring.application.name=catalog-service

server.port=4005

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# URL do Broker do Kafka (usando localhost pois sua API roda mapeada na sua máquina)
spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Serializadores: Transformam os dados Java em bytes para trafegar na rede
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Nomes dos Tópicos que vamos usar (apenas uma variável para facilitar o uso no código)
topico.catalogo.carta-evento=CARTA_EVENTO