spring.application.name=catalog-service
server.port=4005

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# --- CONFIGURAÇÃO DO BANCO DE DADOS ---
# O Spring Boot agora se conecta apenas ao Pgpool, que faz o balanceamento automaticamente.
spring.datasource.url=${CATALOG_SERVICE_SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# --- CONFIGURAÇÃO DO KAFKA ---
spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
topico.catalogo.carta-evento=CARTA_EVENTO
# Resiliencia de Conexao (Failover HikariCP)
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.max-lifetime=600000

