server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: inventory-service-route
              uri: ${INVENTORY_SERVICE_URL}
              predicates:
                - Path=/inventory/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: rewards-service-route
              uri: ${REWARDS_SERVICE_URL}
              predicates:
                - Path=/rewards/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: profile-service-route
              uri: ${PROFILE_SERVICE_URL}
              predicates:
                - Path=/profile/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: catalog-service-route
              uri: ${CATALOG_SERVICE_URL}
              predicates:
                - Path=/catalog/**
              filters:
                - StripPrefix=1
                - JwtValidation
            - id: settlement-service-route
              uri: ${SETTLEMENT_SERVICE_URL}
              predicates:
                - Path=/settlement/**
              filters:
                - StripPrefix=1
                - JwtValidation