events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location / {
            # 1. Tratamento da pré-requisição do navegador (Preflight / OPTIONS)
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
                # Permitindo especificamente os cabeçalhos que sua API utiliza
                add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, User-Id, User-cargo';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            # 2. Injeção do CORS nas requisições diretas (POST, GET, etc.)
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, User-Id, User-cargo' always;

            # 3. Roteamento normal para o API Gateway
            proxy_pass http://api-gateway:4004;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}