syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.quatro.grpc.profile";

service ProfileService{
  rpc transfereDinheiro (TransfereDinheiroRequest) returns (TransfereDinheiroResponse);
  rpc validaSaldoUsuario (ValidaSaldoRequest) returns (ValidaSaldoResponse);
}

message TransfereDinheiroRequest {
  double preco_carta = 1;
  string id_user1 = 2; // Vendedor
  string id_user2 = 3; // Comprador
}

message TransfereDinheiroResponse {
  bool sucesso = 1;
  string mensagem = 2;
}

message ValidaSaldoRequest {
  string id_user = 1;
  double valor_necessario = 2;
}

message ValidaSaldoResponse {
  bool possui_saldo = 1;
}